### ISSUE TITLE
configure with a --prefix still tries to update system-level directories

### ISSUE THREAD

**Issue by seandavi** [ncbi/ngs#14]
Here is what I see after `configure --prefix=/tmp`:

``` sh
make -C ngs-sdk install
make: Entering directory '/tmp/ncbi/ngs/ngs-sdk'
Checking make status of ngs-sdk/language...
Checking make status of ngs-sdk/dispatch...
Checking make status of ngs-sdk/adapter...
Checking make status of object libraries...
Installing libraries to /tmp/lib64
installing 'libngs-sdk.so.1.2.5'... success
installing 'libngs-c++.a.1.2.5'... success
installing 'libngs-adapt-c++.a.1.2.5'... success
Installing includes to /tmp/include
Installing examples to /tmp/share
Updating /usr/include/ngs                   ## NOTICE HERE
Updating /etc/profile.d/ngs-sdk.[c]sh       ## AND HERE
Use $NGS_LIBDIR in your link commands, e.g.:
      ld -L$NGS_LIBDIR -lngs-sdk ...
make: Leaving directory '/tmp/ncbi/ngs/ngs-sdk'
```

For users without admin or root credentials, this is likely to be problematic.

**Comment by aabaker99** [comment]
I have the same issue. I have been maintaining ngs, ncbi-vdb, and sra-tools for Arch Linux. The build process frequently checks if you are root; if you are, it ignores prefix. I remove (via patch[1]) to arrive at the more familiar behavior provided by GNU autoconf. It would be a big help if these (or similar) changes to respect prefix even if configure is run as the root user are made here.

[1] https://github.com/aabaker99/pkgbuilds/blob/master/ngs/ngs.patch

**Comment by seandavi** [comment]
Any thought you would be interested in forking and patching, @aabaker99?  It would potentially help a few of us to have your work in a place where we could test it out.

**Comment by kwrodarmer** [comment]
We will address this today, @seandavi and @aabaker99 .

**Comment by seandavi** [comment]
Great, @kwrodarmer.  Thanks!

**Comment by kwrodarmer** [comment]
By the way - we will try to be more explicit about what changes are made. We do **not** make the updates you see unless you are root. Instead, we print a message about how you can update your environment to have access to the libraries. We **do** install a symlink under /usr/include, and will examine the patch code to see what cases we are missing. @aabaker99, any comments on the types of changes you would like to see would be welcome (not promising, but still!).

**Comment by aabaker99** [comment]
My suggestions are based on my efforts to prepare this software to conform to the packaging standards for Arch Linux and to some extent Debian. I wanted to give this a shot to make the software available for more people, for people where the pre-built binaries are undesirable or maybe don't work on their system.

The best case for maintainers and packagers would be if there was a GNU autoconf configure script that could be used instead of this unique one developed by the ncbi team. I am new but it seems to me that many people that prepare packages for Linux distributions maintain many packages and most of them follow the same build process from GNU so it makes it easy for the maintainer. But, I imagine it would be a big undertaking for your group to make that change. So instead, supporting the same options would be nice. 

The key addition would be to support **--prefix** in the **configure** script. Of course, that option is present already in the ngs **configure**, but its different behavior versus GNU autoconf **configure** is what makes surprises for maintainers. For Arch, the code which checks if you are root and installs to directories like /usr/include breaks the packaging process: Arch uses a command like **chroot** (so I must run configure as root) but files need to be installed to pkgdir/usr/include. For Debian I am less clear on the whole build process, but from what I can tell it is a similar situation. I added my work in progress here [1]. I wanted to try and follow similar steps to my Arch changes to learn and compare to what the other Debian packagers have done. It's incomplete, so it may be confusing and I wouldn't really recommend reading it. Others who are more experienced with Debian packaging have also struggled with the custom configure scripts [2]. The key files to look at there are the **rules** and the **patches**. Anyway, the thing to notice in the **rules** file are the comments complaining about files not ending up in their proper locations (not listening to the **--prefix** option). 

A second nice improvement would be on **make clean**. Debian is more strict about leaving files behind after the build is done, so there is a lot of code in this **rules** file [2] to clean up after the build. I'm guessing that some files are still left behind even after running ngs's **make clean**. So, that would be a nice change from the Debian perspective.

If @tillea can comment, I'm sure he would have many good suggestions as well. He does a lot of great work making bio/med software available for Debian.

[1] https://github.com/aabaker99/debian-builds/tree/master/ngs
[2] https://anonscm.debian.org/cgit/debian-med/ngs-sdk.git/tree/debian

**Comment by tillea** [comment]
On Tue, Aug 23, 2016 at 08:38:16AM -0700, Aaron wrote:
> The best case for maintainers and packagers would be if there was a GNU autoconf configure script that could be used instead of this unique one developed by the ncbi team. I am new but it seems to me that many people that prepare packages for Linux distributions maintain many packages and most of them follow the same build process from GNU so it makes it easy for the maintainer.

I'd offer a few beers if someone would convert tto GNU autoconf.  The
custom build system has taken me hours (if not days) and is the only
reason why Debian is lagging behind upstream sra toolkit that much.

> The key addition would be to support **--prefix** in the **configure** script. Of course, that option is present already in the ngs **configure**, but its different behavior versus GNU autoconf **configure** is what makes surprises for maintainers. For Arch, the code which checks if you are root and installs to directories like /usr/include breaks the packaging process: Arch uses a command like **chroot** (so I must run configure as root) but files need to be installed to pkgdir/usr/include. For Debian I am less clear on the whole build process, but from what I can tell it is a similar situation. I added my work in progress here [1]. I wanted to try and follow similar steps to my Arch changes to learn and compare to what the other Debian packagers have done. It's incomplete, so it may be confusing and I wouldn't really recommend reading it. Others who are more experienced with Debian packaging have also struggled with the custom configure scripts [2]. The key files to look at there are the **rules** and the **patches**. Anyway, the thing to notice in the **rules** file are the comments complaining about files not ending up in their proper locations (not listening to the **--prefix** option). 
> 
> A second nice improvement would be on **make clean**. Debian is more strict about leaving files behind after the build is done, so there is a lot of code in this **rules** file [2] to clean up after the build. I'm guessing that some files are still left behind even after running ngs's **make clean**. So, that would be a nice change from the Debian perspective.

Make clean comes automatically with GNU autoconf.
 
> If @tillea can comment, I'm sure he would have many good suggestions as well. He does a lot of great work making bio/med software available for Debian.

My only comment is: Please use GNU autoconf (or cmake if it might be
more appropriate / easy for you).

Thanks for the effort

      Andreas.
 
> [1] https://github.com/aabaker99/debian-builds/tree/master/ngs
> [2] https://anonscm.debian.org/cgit/debian-med/ngs-sdk.git/tree/debian
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ncbi/ngs/issues/14#issuecomment-241774876

-- 
http://fam-tille.de

**Comment by kwrodarmer** [comment]
So a few comments:

First, our code was developed for cross-platform development. To us that doesn't mean the difference between one Linux distro and another, but between Linux, Windows and MacOS (and others that we supported in the past). We decided against autoconf years ago for this reason.

Second, historically (and currently) most of our users do **not** have admin rights on the systems they use. Our build used to be quite a bit simpler, essentially `make` and then you use the build results directly. Since then, we've added a configuration script exactly to help out users who are used to the standard `./configure; make; sudo make install`.

I agree that we can do more to support the efforts of people who are performing packaging operations, and we can improve our reporting to let you know what we are modifying. In fact, we do not "ignore" `--prefix` when running as root, but we are clearly doing things that defy the customization you need.

Lastly, regarding the `make clean` - what problem are you having? We remove 100% of the produced binaries and object files with make clean... Is there something else you want cleaned?

**Comment by kwrodarmer** [comment]
@tillea - can you give us more information about what you are doing with regard to packaging for Debian? What is the frequency? The lag time?

**Comment by tillea** [comment]
Thanks for the quick response.

On Tue, Aug 23, 2016 at 09:32:07AM -0700, kwrodarmer wrote:
> First, our code was developed for cross-platform development. To us that doesn't mean the difference between one Linux distro and another, but between Linux, Windows and MacOS (and others that we supported in the past). We decided against autoconf years ago for this reason.

In how far does autoconf conflict with the cross-platform development?  Autoconf is available on all these platforms.
 
> Second, historically (and currently) most of our users do **not** have admin rights on the systems they use. Our build used to be quite a bit simpler, essentially `make` and then you use the build results directly. Since then, we've added a configuration script exactly to help out users who are used to the standard `./configure; make; sudo make install`.

Users can just use the --prefix argument to get exactly what you describe.
 
> I agree that we can do more to support the efforts of people who are performing packaging operations, and we can improve our reporting to let you know what we are modifying. In fact, we do not "ignore" `--prefix` when running as root, but we are clearly doing things that defy the customization you need.
> 
> Lastly, regarding the `make clean` - what problem are you having? We remove 100% of the produced binaries and object files with make clean... Is there something else you want cleaned?

In the Debian packaging of ncbi-vdb I'm using this

    https://anonscm.debian.org/cgit/debian-med/ncbi-vdb.git/tree/debian/clean

clean file to cleanup things that are not cleaned by `make clean`.  May be that's rather comparable to `make distclean` of autoconf.

Kind regards

       Andreas.


-- 
http://fam-tille.de

**Comment by kwrodarmer** [comment]
We are preparing announcements regarding an imminent and mandatory switch from HTTP to HTTPS that will require an update to **all** SRA-related software, so timing of releases is seen more important than before.

**Comment by tillea** [comment]
On Tue, Aug 23, 2016 at 09:35:30AM -0700, kwrodarmer wrote:
> @tillea - can you give us more information about what you are doing with regard to packaging for Debian? What is the frequency? The lag time?

My plan is to package each release.  The first lag came due to the fact
that you moved to a new location which our automatic process can't
guess.  Once I realised this I noticed that sra-sdk needs two libraries
(ngs-sdk and ncbi-vdb) which needed separate packaging.  I was fighting
through their build system and while ngs-sdk is in Debian ncbi-vdb is in
the Debian new queue waiting fro processing.  I hope this will be done
soon.

Once this is accepted I can upgrade sra-sdk.  I hope to catch up with
all your releases which becomes way more simple if you either do not
change the build system any more or of you switch to something the
majority in the free software world is happy with (autoconf or cmake
which both are supporting all platforms you mentioned).  From my point
of view using an own written build system is wasting your own and your
downstream times.

Kind regards and thanks for your quick responses

    Andreas.

-- 
http://fam-tille.de

**Comment by tillea** [comment]
On Tue, Aug 23, 2016 at 09:40:19AM -0700, kwrodarmer wrote:
> We are preparing announcements regarding an imminent and mandatory switch from HTTP to HTTPS that will require an update to **all** SRA-related software, so timing of releases is seen more important than before.

I'll package the latest available release if ncbi-vdb is available in
Debian.  This kind of announcements are helpful to let us do sensible
things in any case.  The mailing list for the announcements (which is
the "Maintainer" of the team maintained package) is:

   Debian Med Packaging Team <debian-med-packaging@lists.alioth.debian.org>

Kind regards

     Andreas.

-- 
http://fam-tille.de

**Comment by kwrodarmer** [comment]
So regarding your "clean" script - `make clean` is intended to remove the products of building source, but should not disturb configuration. Perhaps `make distclean` would be appropriate for that as you suggest.

Removal of the litter created inside the krypto directory is something we should have done long ago - and should not be there at all. We'll address that.

As to your insistence on autoconf and/or cmake, we have begun using cmake within our ngs-tools repository and have longer term plans of converting everything to it. However, this is not only a substantial effort, but has a substantial impact on our automated testing processes.

I do encourage you to be in contact with us to let us know what you're doing and what your needs are (hint - autoconf is not a need!) and we will do our best to accommodate.

Thanks for the mailing list - this is very helpful!

**Comment by seandavi** [comment]
@kwrodarmer, I REALLY appreciate the communication here.  And getting the Arch and Debian communities involved is a real bonus.  Thanks for jumping in, @aabaker99 and @tillea.  Just to keep the momentum going, are there actionable items that we should file as specific issues and then refer back to this issue?  Seems like there may have been several.

**Comment by tillea** [comment]
On Tue, Aug 23, 2016 at 09:52:42AM -0700, kwrodarmer wrote:
> ... but should not disturb configuration. Perhaps `make distclean` would be appropriate for that as you suggest.

Yes.
 
> As to your insistence on autoconf and/or cmake, we have begun using cmake within our ngs-tools repository and have longer term plans of converting everything to it. However, this is not only a substantial effort, but has a substantial impact on our automated testing processes.

Using cmake would be good news.  I hope you will be able to solve the issues of the testing process that might be triggered by this change.
 
> I do encourage you to be in contact with us to let us know what you're doing and what your needs are (hint - autoconf is not a need!) and we will do our best to accommodate.

I confirm that autoconf is really not a need - cmake is fine as well.

Regarding what is done to build sra-sdk and its dependencies:  All
packages are maintained in Git.  The patches that are applied to build
the packages can be found here:

ngs-sdk:
   https://anonscm.debian.org/git/debian-med/ngs-sdk.git/tree/debian/patches

ncbi-vdb:
   https://anonscm.debian.org/git/debian-med/ncbi-vdb.git/tree/debian/patches

sra-sdk:
   https://anonscm.debian.org/git/debian-med/sra-sdk.git/tree/debian/patches

> Thanks for the mailing list - this is very helpful!

Good.  Feel free to discuss any issue you might consider important.

Kind regards

       Andreas.

-- 
http://fam-tille.de

**Comment by tillea** [comment]
On Tue, Aug 23, 2016 at 10:28:50AM -0700, Sean Davis wrote:
> @kwrodarmer, I REALLY appreciate the communication here.  And getting the Arch and Debian communities involved is a real bonus.  Thanks for jumping in, @aabaker99 and @tillea.

I confirm that I also really appreciate this discussion that might help
to get rid of stumbling stones in packaging.

> Just to keep the momentum going, are there actionable items that we should file as specific issues and then refer back to this issue?  Seems like there may have been several.

For the moment I'm waiting for ncbi-vdb to become accepted in Debian
(should be easy after I removed jni.h and jni_md.h which has a non-free
license but can be easily replaced by
/usr/lib/jvm/default-java/include/jni.h and
/usr/lib/jvm/default-java/include/linux/jni_md.h, respectively.

Once all preconditions for sra-sdk are available I'll come up with
the remaining issue.

Kind regards

       Andreas.

-- 
http://fam-tille.de

**Comment by outpaddling** [comment]
Have you guys given any thought to switching to a standardized build system such as cmake of GNU configure?

It would take some work, but would solve this issue as well as adding other benefits such as supporting staged installation, which is used by most package managers now.

Cheers,

    Jason

**Comment by tillea** [comment]
Hi,

On Fri, Dec 02, 2016 at 06:23:20AM -0800, outpaddling wrote:
> Have you guys given any thought to switching to a standardized build system such as cmake of GNU configure?
> 
> It would take some work, but would solve this issue as well as adding other benefits such as supporting staged installation, which is used by most package managers now.

I can only support this.  I need again wade throught 2.8.0 build system of sra-sdk (while I have made my way through ncbi-vdb successfully for Debian).  It would be really helpful if this package would not drain so much time for every new release.

Thanks for considering

        Andreas.

-- 
http://fam-tille.de

**Comment by klymenko** [comment]
@seandavi , @aabaker99 , this issue should be fixed by now.
Please confirm.

**Comment by tillea** [comment]
Hi,
On Mon, May 18, 2020 at 04:27:31PM -0700, Andrew Klymenko wrote:
> @seandavi , @aabaker99 , this issue should be fixed by now.
> Please confirm.
I confirm that your build system and our current set of patches builds.
My personal opinion is that if you would save yourself and all your
downstreams a lot of hassle if you would consider an established build
system.
Kind regards, Andreas.
