### ISSUE TITLE
make -C ngs-java fails. 

### ISSUE THREAD

**Issue by samyuktr** [ncbi/ngs#24]
```
make: Entering directory '/mnt/storage/ncbi/ngs/ngs-java'
*** File 'Makefile.config.linux.x86_64' is missing. Please run ./configure
/mnt/storage/ncbi/ngs/ngs-java/Makefile.rules:71: recipe for target 'Makefile.config.linux.x86_64' failed
make: *** [Makefile.config.linux.x86_64] Error 1
make: Leaving directory '/mnt/storage/ncbi/ngs/ngs-java'
```
I'm running this after `./configure` But I just can't seem to get past this step. Am I doing something wrong? Did anyone else face this issue?

**Comment by kwrodarmer** [comment]
Would you mind re-running and pasting your exact command line in the window? You say you're running this after `./configure` but it it isn't visible to us.

**Comment by samyuktr** [comment]
Sure. Here's my command line 

```
$ ./configure
CONFIGURING ngs-sdk
reconfiguring...
running "./configure "...
Configuring NGS-SDK package
checking system type... Linux
checking OS distributor... Ubuntu
checking machine architecture... x86_64
checking for supported architecture... x86_64 (64 bits) is supported
checking for supported OS... Linux (linux) is supported
checking for supported tool chain... gcc tool chain is supported
checking for g++... yes
checking whether gcc accepts -Wno-array-bounds... yes
checking whether g++ accepts -static-libstdc++... no

configure: creating 'ld.linux.exe_cmd.sh'
configure: creating 'Makefile.config.linux.x86_64'
cannot open Makefile.config.linux.x86_64 to write at konfigure.perl line 764.

CONFIGURING ngs-java
Configuring NGS-JAVA package
checking system type... Linux
checking OS distributor... Ubuntu
checking machine architecture... x86_64
checking for supported architecture... x86_64 (64 bits) is supported
checking for supported OS... Linux (linux) is supported
checking for supported tool chain... jdk tool chain is supported
checking for javac... no
configure: error: 'javac' cannot be found

CONFIGURING ngs-python
reconfiguring...
running "./configure "...
Configuring NGS-PYTHON package
checking system type... Linux
checking OS distributor... Ubuntu
checking machine architecture... x86_64
checking for supported architecture... x86_64 (64 bits) is supported
checking for supported OS... Linux (linux) is supported
checking for supported tool chain... gcc tool chain is supported
checking for g++... yes
checking whether gcc accepts -Wno-array-bounds... yes
checking whether g++ accepts -static-libstdc++... no
checking for ngs-sdk package...
	libraries... /usr/local/ngs/ngs-sdk/lib64
libraries: /usr/local/ngs/ngs-sdk/lib64
checking for ncbi-vdb package...
	libraries... /usr/local/ncbi/ncbi-vdb/lib64
libraries: /usr/local/ncbi/ncbi-vdb/lib64

configure: creating 'ld.linux.exe_cmd.sh'
cannot open ld.linux.exe_cmd.sh to write at konfigure.perl line 757, <F> line 1.

$make -C ngs-java
make: Entering directory '/mnt/storage/ncbi/ngs/ngs-java'
*** File 'Makefile.config.linux.x86_64' is missing. Please run ./configure
/mnt/storage/ncbi/ngs/ngs-java/Makefile.rules:71: recipe for target 'Makefile.config.linux.x86_64' failed
make: *** [Makefile.config.linux.x86_64] Error 1
make: Leaving directory '/mnt/storage/ncbi/ngs/ngs-java'
```

**Comment by kwrodarmer** [comment]
You don't have the java SDK installed. You are missing `javac` which means that `ngs` can't be built. Please install the JDK and try again.

**Comment by aboshkin** [comment]
Also, make sure you have write permissions for ./build

**Comment by samyuktr** [comment]
That helped. Thanks a ton!

**Comment by qiaowei-vvjoe** [comment]
Hi @aboshkin @samyuktr 
I guess I have the same problem as you and I don't know if it only because I haven't the permission?Thank you so much in advance.

make -C ngs-sdk install
make: Entering directory `/mnt/disk1/qiaowei/ncbi/ngs/ngs-sdk'
Checking make status of ngs-sdk/language...
Checking make status of ngs-sdk/dispatch...
Checking make status of ngs-sdk/adapter...
Checking make status of object libraries...
mkdir: cannot create directory ‘/usr/local/ngs’: Permission denied
make[1]: *** [/usr/local/ngs/ngs-sdk/lib64] Error 1
make: *** [sdk-libs_inst] Error 2
make: Leaving directory `/mnt/disk1/qiaowei/ncbi/ngs/ngs-sdk'

[qiaowei@clust1 ngs]$ make -C ngs-java install
make: Entering directory `/mnt/disk1/qiaowei/ncbi/ngs/ngs-java'
Checking make status of jars...
mkdir: cannot create directory ‘/usr/local/ngs’: Permission denied
make[1]: *** [/usr/local/ngs/ngs-java/jar] Error 1
make: *** [java_inst] Error 2
make: Leaving directory `/mnt/disk1/qiaowei/ncbi/ngs/ngs-java'

[qiaowei@clust1 ngs]$ make -C ngs-python install
make: Entering directory `/mnt/disk1/qiaowei/ncbi/ngs/ngs-python'
mkdir: cannot create directory ‘/usr/local/ngs’: Permission denied
make[1]: *** [/usr/local/ngs/ngs-python] Error 1
make: *** [install] Error 2
make: Leaving directory `/mnt/disk1/qiaowei/ncbi/ngs/ngs-python'

**Comment by aboshkin** [comment]
Yes. you need write permission to /usr/local/. Try 'sudo make ...' if you are allowed. Otherwise, you may try to install into a different (writeable) directory by running 'configure --prefix=<pathToInstallTo>' and then 'make install', all from the NGS root directory. Run 'configure -h' for full details.

**Comment by qiaowei-vvjoe** [comment]
hi aboshkin @aboshkin  
yes.I don't have the permission.so I need 'configure --prefix=dir',then can I define the dir in this ngs directory?

**Comment by aboshkin** [comment]
@qiaowei-vvjoe, placing the output directory inside you ngs directory will work and you do not need to create it in advance. For example, these two commands will place the binaries in the OUTPUT subdirectory of you ngs directory:

`./configure --prefix=$(pwd)/OUTPUT`
`make install`


When building other NCBI projects that depend on ngs, you will need to specify that directory in their respective configuration command. Foe example, for ncbi-vdb, if it is checked out side-by-side with the ngs directory:

`./configure --with-ngs-sdk-prefix=$(pwd)/../ngs/OUTPUT`

As a side note, I assume you have a good reason to build the binaries from the sources. If not, you might want to download pre-built binaries from guthub: https://github.com/ncbi/ngs/wiki/Downloads

**Comment by qiaowei-vvjoe** [comment]
hi aboshkin @aboshkin 
Thank you so much for your detail explains. 

As for me, I agree the first part and I do follow the command:
./configure --prefix=$(pwd)/OUTPUT
make install

But for the other NCBI projects which depend on ngs, I do not too much understand.For example, for ncbi-vdb, should I configure it by which one?
 ./configure --with-ngs-sdk-prefix=$(pwd)/../ngs/OUTPUT
./configure --with-ngs-vdb-prefix=$(pwd)/../ngs/OUTPUT

And for your side note, you mean that I can directly download the binaries from that webside if I feel difficult by download source code then configure then make install(the method that I doing now)?

I am so sorry for these stupid questions.
Thank you so much in advance.

**Comment by qiaowei-vvjoe** [comment]
@aboshkin 
And I tried the `./configure --with-ngs-sdk-prefix=$(pwd)/../ngs/OUTPUT`to configure ncbi-vdb,but when I `make`,it shows 

`make[3]: *** No rule to make target `/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/kns/cloud.h', needed by `manager.pic.o'.  Stop.
make[3]: Leaving directory `/mnt/disk1/qiaowei/ncbi-outdir/ncbi-vdb/linux/gcc/x86_64/rel/obj/libs/kns'
make[2]: *** [stdcompile] Error 2
make[2]: Leaving directory `/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/kns'
make[1]: *** [kns] Error 2
make[1]: Leaving directory `/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs'
make: *** [libs] Error 2`

and `make install`
it shows

`Checking make status of object libraries...
NOTE - internal library libkff cannot be built: It requires 'libmagic' and its development headers.
make[4]: *** No rule to make target `/mnt/disk1/qiaowei/ncbi/ncbi-vdb/libs/kns/cloud.h', needed by `manager.pic.o'.  Stop.
make[3]: *** [stdcompile] Error 2
make[2]: *** [kns] Error 2
make[1]: *** [libs] Error 2
make: *** [install] Error 2`

did I do anything wrong?

**Comment by kwrodarmer** [comment]
Hi @qiaowei-vvjoe  - could you please explain why use of our binary distribution is not useful for you?

**Comment by qiaowei-vvjoe** [comment]
@kwrodarmer 
Hi 
I am so sorry but I just want to test myself to install using source code,It doesn't mean your binary distribution is not useful for me. Because I am not too much experience in install using source code and I usually install by binary before, now I have a chance to install in another account so I decide to  have a try.I am so sorry if I troubled you.

**Comment by kwrodarmer** [comment]
No, no! No trouble at all. The question was whether there was a problem with the binaries. You are welcome to build from source.

**Comment by aboshkin** [comment]
@qiaowei-vvjoe , the error you are seeing in ncbvi-vdb indicates the presence of outputs from a prior build that was done using older sources. Run `make clean` in your ncbi-vdb directory and then try `make` again.

Both ncbi-vdb and sra-tools use the configuration flag --with-ngs-sdk-prefix to locate binaries built by the ngs project. The flag --with-vdb-prefix is only used to configure sra-tools, in cases where ncbi-vdb binaries have been created in a non-standard location.
